### Georgia Model
This notebook uses the model that is only trained to the Georgia data and validates it on the California and Georgia data.

In [2]:
#importing the data
import pandas as pd
import numpy as np
from pathlib import Path
import pickle  # for saving and loading models
from lightgbm.sklearn import LGBMRegressor
from sklearn.metrics import r2_score  # for R squared
from sklearn.metrics import mean_squared_error as rmse_score  # for root mean squared error

ModuleNotFoundError: No module named 'lightgbm'

In [ ]:
#importing the Georgia data
PARENT = "Predicing_House_Prices"
path = Path(PARENT).parent / "../Data/X_train_GA.csv"
X_train_GA = pd.read_csv(path)

path2 = Path(PARENT).parent / "../Data/X_test_GA.csv"
X_test_GA = pd.read_csv(path2)

path3 = Path(PARENT).parent / "../Data/y_train_GA.csv"
y_train_GA = pd.read_csv(path3)

path4 = Path(PARENT).parent / "../Data/y_test_GA.csv"
y_test_GA= pd.read_csv(path4)

path9 = Path(PARENT).parent / "../Data/X_train_GA_noGeo.csv"
X_train_GA_NoGeo = pd.read_csv(path9)

In [ ]:
X_train_GA_NoGeo

,Unnamed: 0,yearBuilt,livingArea,bathrooms,bedrooms,parking,garageSpaces,hasGarage,pool,spa,...,lotAreaUnits_sqft,levels_one level,levels_others,levels_split level,levels_two levels,homeType_APARTMENT,homeType_CONDO,homeType_MULTI_FAMILY,homeType_SINGLE_FAMILY,homeType_TOWNHOUSE
0,0,1.230521,-0.411190,0.088911,-0.507801,1,-0.712716,0,0,0,...,1,0,1,0,0,0,0,0,1,0
1,1,-0.940911,-0.764134,-1.390290,-1.369029,1,-0.712716,0,0,0,...,1,0,1,0,0,0,0,0,1,0
2,2,-2.853068,0.242540,-0.650690,-0.507801,0,-0.712716,0,0,0,...,0,0,1,0,0,0,0,0,1,0
3,3,1.230521,-0.419798,-0.650690,-1.369029,1,0.222734,1,0,0,...,1,1,0,0,0,0,0,0,1,0
4,4,0.063781,-0.081033,0.088911,-0.507801,1,1.158184,1,0,0,...,1,0,1,0,0,0,0,0,1,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
5585,5585,0.679560,0.616245,0.828511,1.214655,1,1.158184,1,0,0,...,0,0,0,0,1,0,0,0,1,0
5586,5586,0.679560,3.568413,4.526513,2.937112,1,3.029084,1,0,0,...,0,0,1,0,0,0,0,0,1,0
5587,5587,0.063781,1.542912,2.307712,1.214655,1,1.158184,1,1,0,...,0,0,0,0,1,0,0,0,1,0
5588,5588,1.036064,1.616336,1.568112,0.353427,1,-0.712716,1,0,0,...,0,0,0,0,1,0,0,0,1,0
5589,5589,-0.876092,-0.534239,-0.650690,-0.507801,1,0.222734,1,0,0,...,0,1,0,0,0,0,0,0,1,0

In [ ]:
#importing the California data
path5 = Path(PARENT).parent / "../Data/X_train_CA.csv"
X_train_CA = pd.read_csv(path5)

path6 = Path(PARENT).parent / "../Data/X_test_CA.csv"
X_test_CA = pd.read_csv(path6)

path7 = Path(PARENT).parent / "../Data/y_train_CA.csv"
y_train_CA = pd.read_csv(path7)

path8 = Path(PARENT).parent / "../Data/y_test_CA.csv"
y_test_CA= pd.read_csv(path8)

path10 = Path(PARENT).parent / "../Data/X_train_CA_noGeo.csv"
X_train_CA2 = pd.read_csv(path10)

In [ ]:
#dropping unnamed column
X_train_GA  = X_train_GA.drop(columns="Unnamed: 0")
X_train_GA_NoGeo = X_train_GA_NoGeo.drop(columns="Unnamed: 0")
X_test_GA  = X_test_GA.drop(columns="Unnamed: 0")
y_train_GA = y_train_GA.drop(columns="Unnamed: 0")
y_test_GA = y_test_GA.drop(columns="Unnamed: 0")

X_train_CA  = X_train_CA .drop(columns="Unnamed: 0")
X_train_CA2 = X_train_CA2.drop(columns="Unnamed: 0")
X_test_CA  = X_test_CA.drop(columns="Unnamed: 0")
y_train_CA = y_train_CA.drop(columns="Unnamed: 0")
y_test_CA = y_test_CA.drop(columns="Unnamed: 0")

In [ ]:
X_train_CA2

,yearBuilt,livingArea,bathrooms,bedrooms,parking,garageSpaces,hasGarage,pool,spa,isNewConstruction,...,lotAreaUnits_sqft,levels_one level,levels_others,levels_split level,levels_two levels,homeType_APARTMENT,homeType_CONDO,homeType_MULTI_FAMILY,homeType_SINGLE_FAMILY,homeType_TOWNHOUSE
0,-0.826714,-0.010349,0.243472,0.522588,0,-0.965336,0,0,0,0,...,1,1,0,0,0,0,0,0,1,0
1,0.822866,-0.018776,-0.489433,-0.292440,1,0.615787,1,0,0,0,...,1,1,0,0,0,0,0,0,1,0
2,-1.902527,-0.024058,-1.222339,-0.292440,0,-0.965336,0,0,0,0,...,0,1,0,0,0,0,0,0,1,0
3,0.535983,0.008023,0.243472,0.522588,1,1.406348,1,0,1,0,...,1,0,0,0,1,0,0,0,1,0
4,-0.503970,-0.011501,0.243472,0.522588,1,0.615787,1,0,0,0,...,0,1,0,0,0,0,0,0,1,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
16193,0.392541,0.012518,0.976378,0.522588,1,-0.965336,0,1,1,0,...,0,0,1,0,0,0,0,0,1,0
16194,1.540075,-0.002315,0.243472,0.522588,1,1.406348,1,0,0,0,...,1,0,0,0,1,0,0,0,1,0
16195,-1.328760,-0.023861,-0.489433,-1.107469,1,-0.174775,1,0,0,0,...,1,1,0,0,0,0,0,0,1,0
16196,0.894587,-0.019956,-0.489433,-0.292440,1,-0.174775,1,0,0,0,...,1,1,0,0,0,0,0,0,1,0
16197,1.073889,0.006731,0.243472,0.522588,1,0.615787,1,1,1,0,...,1,0,0,0,1,0,0,0,1,0

In [ ]:
#dropping all state, city, and county columns for training GA data
X_train_GA2 = X_train_GA[X_train_GA.columns.drop(list(X_train_GA.filter(regex='state_')))]
X_train_GA3 = X_train_GA2[X_train_GA2.columns.drop(list(X_train_GA2.filter(regex='city_')))]
X_train_GA4 = X_train_GA3[X_train_GA3.columns.drop(list(X_train_GA3.filter(regex='county_')))]
X_train_GA4

,yearBuilt,livingArea,bathrooms,bedrooms,parking,garageSpaces,hasGarage,pool,spa,isNewConstruction,...,lotAreaUnits_sqft,levels_one level,levels_others,levels_split level,levels_two levels,homeType_APARTMENT,homeType_CONDO,homeType_MULTI_FAMILY,homeType_SINGLE_FAMILY,homeType_TOWNHOUSE
0,1.230521,-0.411190,0.088911,-0.507801,1,-0.712716,0,0,0,1,...,1,0,1,0,0,0,0,0,1,0
1,-0.940911,-0.764134,-1.390290,-1.369029,1,-0.712716,0,0,0,0,...,1,0,1,0,0,0,0,0,1,0
2,-2.853068,0.242540,-0.650690,-0.507801,0,-0.712716,0,0,0,0,...,0,0,1,0,0,0,0,0,1,0
3,1.230521,-0.419798,-0.650690,-1.369029,1,0.222734,1,0,0,1,...,1,1,0,0,0,0,0,0,1,0
4,0.063781,-0.081033,0.088911,-0.507801,1,1.158184,1,0,0,0,...,1,0,1,0,0,0,0,0,1,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
5585,0.679560,0.616245,0.828511,1.214655,1,1.158184,1,0,0,0,...,0,0,0,0,1,0,0,0,1,0
5586,0.679560,3.568413,4.526513,2.937112,1,3.029084,1,0,0,0,...,0,0,1,0,0,0,0,0,1,0
5587,0.063781,1.542912,2.307712,1.214655,1,1.158184,1,1,0,0,...,0,0,0,0,1,0,0,0,1,0
5588,1.036064,1.616336,1.568112,0.353427,1,-0.712716,1,0,0,0,...,0,0,0,0,1,0,0,0,1,0
5589,-0.876092,-0.534239,-0.650690,-0.507801,1,0.222734,1,0,0,0,...,0,1,0,0,0,0,0,0,1,0

In [ ]:
#dropping all state, city, and county columns for testing GA data
X_test_GA2 = X_test_GA[X_test_GA.columns.drop(list(X_test_GA.filter(regex='state_')))]
X_test_GA3 = X_test_GA2[X_test_GA2.columns.drop(list(X_test_GA2.filter(regex='city_')))]
X_test_GA4 = X_test_GA3[X_test_GA3.columns.drop(list(X_test_GA3.filter(regex='county_')))]
X_test_GA4

,yearBuilt,livingArea,bathrooms,bedrooms,parking,garageSpaces,hasGarage,pool,spa,isNewConstruction,...,lotAreaUnits_sqft,levels_one level,levels_others,levels_split level,levels_two levels,homeType_APARTMENT,homeType_CONDO,homeType_MULTI_FAMILY,homeType_SINGLE_FAMILY,homeType_TOWNHOUSE
0,-0.260313,-0.240542,0.088911,-0.507801,1,-0.712716,0,0,0,0,...,0,1,0,0,0,0,0,0,1,0
1,1.198111,0.536744,0.088911,0.353427,0,-0.712716,1,0,0,0,...,0,0,1,0,0,0,0,0,1,0
2,1.003655,-0.247631,0.828511,-0.507801,1,1.158184,1,0,0,0,...,1,0,1,0,0,0,0,0,0,1
3,-0.584408,0.508894,0.088911,0.353427,1,1.158184,1,0,0,0,...,0,0,0,0,1,0,0,0,1,0
4,0.549923,-0.572724,-0.650690,-0.507801,1,-0.712716,1,0,0,0,...,0,1,0,0,0,0,0,0,1,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
2391,-0.940911,-0.812746,-1.390290,-1.369029,0,-0.712716,0,0,0,0,...,0,1,0,0,0,0,0,0,1,0
2392,-0.389951,-0.183828,-0.650690,0.353427,1,1.158184,1,0,0,0,...,0,0,0,0,1,0,0,0,1,0
2393,0.128600,-0.584877,0.088911,-0.507801,1,-0.712716,1,0,0,0,...,0,1,0,0,0,0,0,0,1,0
2394,0.809198,-0.551456,-0.650690,-1.369029,1,-0.712716,1,0,0,0,...,1,0,0,0,1,0,0,0,0,1
2395,0.744379,0.163546,0.088911,-0.507801,1,1.158184,1,1,1,0,...,0,0,1,0,0,0,0,0,1,0

In [ ]:
#dropping all state, city, and county columns training CA data
X_train_CA2 = X_train_CA[X_train_CA.columns.drop(list(X_train_CA.filter(regex='state_')))]
X_train_CA3 = X_train_CA2[X_train_CA2.columns.drop(list(X_train_CA2.filter(regex='city_')))]
X_train_CA4 = X_train_CA3[X_train_CA3.columns.drop(list(X_train_CA3.filter(regex='county_')))]
X_train_CA4

,yearBuilt,livingArea,bathrooms,bedrooms,parking,garageSpaces,hasGarage,pool,spa,isNewConstruction,...,lotAreaUnits_sqft,levels_one level,levels_others,levels_split level,levels_two levels,homeType_APARTMENT,homeType_CONDO,homeType_MULTI_FAMILY,homeType_SINGLE_FAMILY,homeType_TOWNHOUSE
0,-0.826714,-0.010349,0.243472,0.522588,0,-0.965336,0,0,0,0,...,1,1,0,0,0,0,0,0,1,0
1,0.822866,-0.018776,-0.489433,-0.292440,1,0.615787,1,0,0,0,...,1,1,0,0,0,0,0,0,1,0
2,-1.902527,-0.024058,-1.222339,-0.292440,0,-0.965336,0,0,0,0,...,0,1,0,0,0,0,0,0,1,0
3,0.535983,0.008023,0.243472,0.522588,1,1.406348,1,0,1,0,...,1,0,0,0,1,0,0,0,1,0
4,-0.503970,-0.011501,0.243472,0.522588,1,0.615787,1,0,0,0,...,0,1,0,0,0,0,0,0,1,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
16193,0.392541,0.012518,0.976378,0.522588,1,-0.965336,0,1,1,0,...,0,0,1,0,0,0,0,0,1,0
16194,1.540075,-0.002315,0.243472,0.522588,1,1.406348,1,0,0,0,...,1,0,0,0,1,0,0,0,1,0
16195,-1.328760,-0.023861,-0.489433,-1.107469,1,-0.174775,1,0,0,0,...,1,1,0,0,0,0,0,0,1,0
16196,0.894587,-0.019956,-0.489433,-0.292440,1,-0.174775,1,0,0,0,...,1,1,0,0,0,0,0,0,1,0
16197,1.073889,0.006731,0.243472,0.522588,1,0.615787,1,1,1,0,...,1,0,0,0,1,0,0,0,1,0

In [ ]:
#dropping all state, city, and county columns for testing CA data
X_test_CA2 = X_test_CA[X_test_CA.columns.drop(list(X_test_CA.filter(regex='state_')))]
X_test_CA3 = X_test_CA2[X_test_CA2.columns.drop(list(X_test_CA2.filter(regex='city_')))]
X_test_CA4 = X_test_CA3[X_test_CA3.columns.drop(list(X_test_CA3.filter(regex='county_')))]
X_test_CA4

,yearBuilt,livingArea,bathrooms,bedrooms,parking,garageSpaces,hasGarage,pool,spa,isNewConstruction,...,lotAreaUnits_sqft,levels_one level,levels_others,levels_split level,levels_two levels,homeType_APARTMENT,homeType_CONDO,homeType_MULTI_FAMILY,homeType_SINGLE_FAMILY,homeType_TOWNHOUSE
0,1.109750,0.007798,0.243472,-0.292440,0,0.615787,1,0,0,0,...,0,1,0,0,0,0,0,0,1,0
1,-0.360528,-0.026361,-1.222339,-1.107469,0,-0.965336,0,0,0,0,...,1,0,1,0,0,0,0,0,1,0
2,-0.037784,-0.015658,0.243472,-0.292440,0,-0.965336,0,0,0,0,...,1,0,1,0,0,0,1,0,0,0
3,0.571843,-0.020097,-0.489433,-1.107469,1,0.615787,1,0,0,0,...,1,0,0,0,1,0,1,0,0,0
4,-0.432249,0.000551,0.243472,1.337617,1,0.615787,1,1,0,0,...,0,0,0,0,1,0,0,0,1,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
6938,-1.579783,-0.016389,-0.489433,0.522588,0,-0.965336,0,0,0,0,...,1,1,0,0,0,0,0,0,1,0
6939,1.073889,-0.006107,0.243472,-0.292440,0,0.615787,1,0,0,0,...,0,1,0,0,0,0,0,0,1,0
6940,-1.687365,-0.009590,0.976378,0.522588,1,-0.965336,0,0,0,0,...,0,0,1,0,0,0,0,0,1,0
6941,-0.324668,-0.016066,-0.489433,-0.292440,0,-0.965336,0,0,0,0,...,1,0,0,0,1,0,0,0,1,0
6942,0.464262,-0.017891,-0.489433,-0.292440,1,0.615787,1,0,0,0,...,1,1,0,0,0,0,0,0,1,0

In [ ]:
#this function reads in the model's pickle file
def load_obj(filename):
    try:
        with open(filename, "rb") as f:
            return pickle.load(f)
    except Exception as ex:
        print("Error:", ex)

In [ ]:
#reading in the model
lgbm_using_GA = load_obj('../models/lgbm_using_GA.pickle')

In [ ]:
#training the model on the GA data
lgbm_using_GA.fit(X_train_GA_NoGeo, y_train_GA)

NameError: name 'lgbm_using_GA' is not defined

In [ ]:
#testing the model on the Georgia Data
preds= lgbm_using_GA.predict(X_test_GA4)

print("Mean Squared Error:", format(rmse_score(y_test_GA, preds)))
print("R Squared:", format(lgbm_using_GA.r2_score(X_test_GA4, y_test_GA)))

AttributeError: 'NoneType' object has no attribute 'predict'

In [ ]:
#testing the model on the California Data
preds2= lgbm_using_GA.predict(X_test_CA4)

print("Mean Squared Error:", format(rmse_score(y_test_CA, preds2)))
print("R Squared:", format(lgbm_using_GA.r2_score(X_test_CA4, y_test_CA)))